name: flutter_uvc_camera
description: flutter android uvc camera plugin.
version: 0.0.1
homepage: https://github.com/chenyeju295/flutter_uvc_camera

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.chenyeju
        pluginClass: FlutterUVCCameraPlugin
